(function() {
    angular.module('highnoon').service('Tardis', [function() {
        var Tardis = {
            whereIsHighNoon: whereIsHighNoon
        };

        function whereIsHighNoon() {
            var highNoonCityList = [];
            var now = new Date();
            var currentUtcTimeFractional = now.getUTCHours() + (now.getUTCMinutes() / 60);

            timeZoneTable.forEach(function(tableItem) {
                var currentZoneHours = currentUtcTimeFractional + tableItem.utcOffset;
                if (currentZoneHours >= 12 && currentZoneHours < 12.5) {
                    highNoonCityList.push(tableItem.cityName);
                }
            });

            return highNoonCityList;
        }

        var timeZoneTable = [{
            "cityName": "A Coruña",
            "utcOffset": 2
        }, {
            "cityName": "Hagåtña",
            "utcOffset": 10
        }, {
            "cityName": "Oklahoma City",
            "utcOffset": -5
        }, {
            "cityName": "Abidjan",
            "utcOffset": 0
        }, {
            "cityName": "Hai Phong",
            "utcOffset": 7
        }, {
            "cityName": "Omsk",
            "utcOffset": 6
        }, {
            "cityName": "Abu Dhabi",
            "utcOffset": 4
        }, {
            "cityName": "Halifax",
            "utcOffset": -3
        }, {
            "cityName": "Oral",
            "utcOffset": 5
        }, {
            "cityName": "Abuja",
            "utcOffset": 1
        }, {
            "cityName": "Hamamatsu",
            "utcOffset": 9
        }, {
            "cityName": "Orlando",
            "utcOffset": -4
        }, {
            "cityName": "Acapulco",
            "utcOffset": -5
        }, {
            "cityName": "Hamburg",
            "utcOffset": 2
        }, {
            "cityName": "Osaka",
            "utcOffset": 9
        }, {
            "cityName": "Accra",
            "utcOffset": 0
        }, {
            "cityName": "Hamilton (Bermuda)",
            "utcOffset": -3
        }, {
            "cityName": "Oslo",
            "utcOffset": 2
        }, {
            "cityName": "Adak",
            "utcOffset": -9
        }, {
            "cityName": "Hamilton (CA-ON)",
            "utcOffset": -4
        }, {
            "cityName": "Ottawa",
            "utcOffset": -4
        }, {
            "cityName": "Adamstown",
            "utcOffset": -8
        }, {
            "cityName": "Hangzhou",
            "utcOffset": 8
        }, {
            "cityName": "Ouagadougou",
            "utcOffset": 0
        }, {
            "cityName": "Addis Ababa",
            "utcOffset": 3
        }, {
            "cityName": "Hanoi",
            "utcOffset": 7
        }, {
            "cityName": "Palangka Raya",
            "utcOffset": 7
        }, {
            "cityName": "Adelaide",
            "utcOffset": 9.5
        }, {
            "cityName": "Happy Valley-Goose Bay",
            "utcOffset": -3
        }, {
            "cityName": "Palembang",
            "utcOffset": 7
        }, {
            "cityName": "Aden",
            "utcOffset": 3
        }, {
            "cityName": "Harare",
            "utcOffset": 2
        }, {
            "cityName": "Palikir",
            "utcOffset": 11
        }, {
            "cityName": "Agra",
            "utcOffset": 5.5
        }, {
            "cityName": "Harbin",
            "utcOffset": 8
        }, {
            "cityName": "Palma",
            "utcOffset": 2
        }, {
            "cityName": "Aguascalientes",
            "utcOffset": -5
        }, {
            "cityName": "Harrisburg",
            "utcOffset": -4
        }, {
            "cityName": "Palu",
            "utcOffset": 8
        }, {
            "cityName": "Ahmedabad",
            "utcOffset": 5.5
        }, {
            "cityName": "Hartford",
            "utcOffset": -4
        }, {
            "cityName": "Panama",
            "utcOffset": -5
        }, {
            "cityName": "Ahmedgarh",
            "utcOffset": 5.5
        }, {
            "cityName": "Havana",
            "utcOffset": -4
        }, {
            "cityName": "Papeete",
            "utcOffset": -10
        }, {
            "cityName": "Akron",
            "utcOffset": -4
        }, {
            "cityName": "Helena",
            "utcOffset": -6
        }, {
            "cityName": "Paramaribo",
            "utcOffset": -3
        }, {
            "cityName": "Albany",
            "utcOffset": -4
        }, {
            "cityName": "Helsinki",
            "utcOffset": 3
        }, {
            "cityName": "Paris",
            "utcOffset": 2
        }, {
            "cityName": "Albuquerque",
            "utcOffset": -6
        }, {
            "cityName": "Hermosillo",
            "utcOffset": -7
        }, {
            "cityName": "Patna",
            "utcOffset": 5.5
        }, {
            "cityName": "Alert",
            "utcOffset": -4
        }, {
            "cityName": "Himeji",
            "utcOffset": 9
        }, {
            "cityName": "Pensacola",
            "utcOffset": -5
        }, {
            "cityName": "Alexandria",
            "utcOffset": 2
        }, {
            "cityName": "Hiroshima",
            "utcOffset": 9
        }, {
            "cityName": "Perm",
            "utcOffset": 5
        }, {
            "cityName": "Algiers",
            "utcOffset": 1
        }, {
            "cityName": "Ho Chi Minh",
            "utcOffset": 7
        }, {
            "cityName": "Perth",
            "utcOffset": 8
        }, {
            "cityName": "Alice Springs",
            "utcOffset": 9.5
        }, {
            "cityName": "Hobart",
            "utcOffset": 10
        }, {
            "cityName": "Petropavlovsk-Kamchatsky",
            "utcOffset": 12
        }, {
            "cityName": "Almaty",
            "utcOffset": 6
        }, {
            "cityName": "Hong Kong",
            "utcOffset": 8
        }, {
            "cityName": "Pevek",
            "utcOffset": 12
        }, {
            "cityName": "Alofi",
            "utcOffset": -11
        }, {
            "cityName": "Honiara",
            "utcOffset": 11
        }, {
            "cityName": "Philadelphia",
            "utcOffset": -4
        }, {
            "cityName": "Amman",
            "utcOffset": 3
        }, {
            "cityName": "Honolulu",
            "utcOffset": -10
        }, {
            "cityName": "Phnom Penh",
            "utcOffset": 7
        }, {
            "cityName": "Amsterdam",
            "utcOffset": 2
        }, {
            "cityName": "Houston",
            "utcOffset": -5
        }, {
            "cityName": "Phoenix",
            "utcOffset": -7
        }, {
            "cityName": "Amsterdam Island",
            "utcOffset": 5
        }, {
            "cityName": "Hovd",
            "utcOffset": 8
        }, {
            "cityName": "Pierre",
            "utcOffset": -5
        }, {
            "cityName": "Anadyr",
            "utcOffset": 12
        }, {
            "cityName": "Hyderabad",
            "utcOffset": 5.5
        }, {
            "cityName": "Podgorica",
            "utcOffset": 2
        }, {
            "cityName": "Anantapur",
            "utcOffset": 5.5
        }, {
            "cityName": "Incheon",
            "utcOffset": 9
        }, {
            "cityName": "Pond Inlet",
            "utcOffset": -4
        }, {
            "cityName": "Anchorage",
            "utcOffset": -8
        }, {
            "cityName": "Indianapolis",
            "utcOffset": -4
        }, {
            "cityName": "Ponta Delgada",
            "utcOffset": 0
        }, {
            "cityName": "Andorra La Vella",
            "utcOffset": 2
        }, {
            "cityName": "Indore",
            "utcOffset": 5.5
        }, {
            "cityName": "Pontianak",
            "utcOffset": 7
        }, {
            "cityName": "Ankara",
            "utcOffset": 3
        }, {
            "cityName": "Innsbruck",
            "utcOffset": 2
        }, {
            "cityName": "Port-au-Prince",
            "utcOffset": -5
        }, {
            "cityName": "Annapolis",
            "utcOffset": -4
        }, {
            "cityName": "Inuvik",
            "utcOffset": -6
        }, {
            "cityName": "Port-aux-Francais",
            "utcOffset": 5
        }, {
            "cityName": "Anshan",
            "utcOffset": 8
        }, {
            "cityName": "Iqaluit",
            "utcOffset": -4
        }, {
            "cityName": "Port Louis",
            "utcOffset": 4
        }, {
            "cityName": "Antananarivo",
            "utcOffset": 3
        }, {
            "cityName": "Irkutsk",
            "utcOffset": 8
        }, {
            "cityName": "Port Moresby",
            "utcOffset": 10
        }, {
            "cityName": "Apia",
            "utcOffset": 13
        }, {
            "cityName": "Islamabad",
            "utcOffset": 5
        }, {
            "cityName": "Port of Spain",
            "utcOffset": -4
        }, {
            "cityName": "Aqtobe",
            "utcOffset": 5
        }, {
            "cityName": "Istanbul",
            "utcOffset": 3
        }, {
            "cityName": "Port Vila",
            "utcOffset": 11
        }, {
            "cityName": "Ashgabat",
            "utcOffset": 5
        }, {
            "cityName": "Ittoqqortoormiit",
            "utcOffset": 0
        }, {
            "cityName": "Portland",
            "utcOffset": -7
        }, {
            "cityName": "Asmara",
            "utcOffset": 3
        }, {
            "cityName": "Izhevsk",
            "utcOffset": 4
        }, {
            "cityName": "Porto",
            "utcOffset": 1
        }, {
            "cityName": "Astana",
            "utcOffset": 6
        }, {
            "cityName": "Izmir",
            "utcOffset": 3
        }, {
            "cityName": "Porto Novo",
            "utcOffset": 1
        }, {
            "cityName": "Asuncion",
            "utcOffset": -4
        }, {
            "cityName": "Jackson",
            "utcOffset": -5
        }, {
            "cityName": "Prague",
            "utcOffset": 2
        }, {
            "cityName": "Athens",
            "utcOffset": 3
        }, {
            "cityName": "Jacksonville",
            "utcOffset": -4
        }, {
            "cityName": "Praia",
            "utcOffset": -1
        }, {
            "cityName": "Atlanta",
            "utcOffset": -4
        }, {
            "cityName": "Jaipur",
            "utcOffset": 5.5
        }, {
            "cityName": "Pretoria",
            "utcOffset": 2
        }, {
            "cityName": "Auckland",
            "utcOffset": 12
        }, {
            "cityName": "Jakarta",
            "utcOffset": 7
        }, {
            "cityName": "Pristina",
            "utcOffset": 2
        }, {
            "cityName": "Augusta",
            "utcOffset": -4
        }, {
            "cityName": "Jamestown",
            "utcOffset": 0
        }, {
            "cityName": "Providence",
            "utcOffset": -4
        }, {
            "cityName": "Austin",
            "utcOffset": -5
        }, {
            "cityName": "Jayapura",
            "utcOffset": 9
        }, {
            "cityName": "Puerto Vallarta",
            "utcOffset": -5
        }, {
            "cityName": "Baghdad",
            "utcOffset": 3
        }, {
            "cityName": "Jeddah",
            "utcOffset": 3
        }, {
            "cityName": "Pune",
            "utcOffset": 5.5
        }, {
            "cityName": "Bahawalpur",
            "utcOffset": 5
        }, {
            "cityName": "Jefferson City",
            "utcOffset": -5
        }, {
            "cityName": "Punta Arenas",
            "utcOffset": -3
        }, {
            "cityName": "Baker Island",
            "utcOffset": -12
        }, {
            "cityName": "Jerusalem",
            "utcOffset": 3
        }, {
            "cityName": "Pyongyang",
            "utcOffset": 8.5
        }, {
            "cityName": "Baker Lake",
            "utcOffset": -5
        }, {
            "cityName": "Jilin",
            "utcOffset": 8
        }, {
            "cityName": "Qaanaaq",
            "utcOffset": -2
        }, {
            "cityName": "Baku",
            "utcOffset": 4
        }, {
            "cityName": "Jinan",
            "utcOffset": 8
        }, {
            "cityName": "Qiqihar",
            "utcOffset": 8
        }, {
            "cityName": "Balikpapan",
            "utcOffset": 8
        }, {
            "cityName": "Jinzhou",
            "utcOffset": 8
        }, {
            "cityName": "Québec",
            "utcOffset": -4
        }, {
            "cityName": "Baltimore",
            "utcOffset": -4
        }, {
            "cityName": "Johannesburg",
            "utcOffset": 2
        }, {
            "cityName": "Quezon",
            "utcOffset": 8
        }, {
            "cityName": "Bamako",
            "utcOffset": 0
        }, {
            "cityName": "Juba",
            "utcOffset": 3
        }, {
            "cityName": "Quito",
            "utcOffset": -5
        }, {
            "cityName": "Bandar Seri Begawan",
            "utcOffset": 8
        }, {
            "cityName": "Juneau",
            "utcOffset": -8
        }, {
            "cityName": "Rabat",
            "utcOffset": 1
        }, {
            "cityName": "Bandung",
            "utcOffset": 7
        }, {
            "cityName": "Kabul",
            "utcOffset": 4.5
        }, {
            "cityName": "Raleigh",
            "utcOffset": -4
        }, {
            "cityName": "Bangkok",
            "utcOffset": 7
        }, {
            "cityName": "Kagoshima",
            "utcOffset": 9
        }, {
            "cityName": "Rapid City",
            "utcOffset": -6
        }, {
            "cityName": "Bangui",
            "utcOffset": 1
        }, {
            "cityName": "Kaliningrad",
            "utcOffset": 2
        }, {
            "cityName": "Rarotonga",
            "utcOffset": -10
        }, {
            "cityName": "Banjul",
            "utcOffset": 0
        }, {
            "cityName": "Kampala",
            "utcOffset": 3
        }, {
            "cityName": "Rasht",
            "utcOffset": 4.5
        }, {
            "cityName": "Baotou",
            "utcOffset": 8
        }, {
            "cityName": "Kangerlussuaq",
            "utcOffset": -2
        }, {
            "cityName": "Rawalpindi",
            "utcOffset": 5
        }, {
            "cityName": "Barcelona",
            "utcOffset": 2
        }, {
            "cityName": "Kano",
            "utcOffset": 1
        }, {
            "cityName": "Recife",
            "utcOffset": -3
        }, {
            "cityName": "Barnaul",
            "utcOffset": 7
        }, {
            "cityName": "Kãnpur",
            "utcOffset": 5.5
        }, {
            "cityName": "Regina",
            "utcOffset": -6
        }, {
            "cityName": "Basse-Terre (Guadeloupe)",
            "utcOffset": -4
        }, {
            "cityName": "Kansas City",
            "utcOffset": -5
        }, {
            "cityName": "Resolute Bay",
            "utcOffset": -5
        }, {
            "cityName": "Basseterre (St. Kitts)",
            "utcOffset": -4
        }, {
            "cityName": "Karachi",
            "utcOffset": 5
        }, {
            "cityName": "Reykjavik",
            "utcOffset": 0
        }, {
            "cityName": "Baton Rouge",
            "utcOffset": -5
        }, {
            "cityName": "Kathmandu",
            "utcOffset": 5.75
        }, {
            "cityName": "Richmond",
            "utcOffset": -4
        }, {
            "cityName": "Beijing",
            "utcOffset": 8
        }, {
            "cityName": "Kawasaki",
            "utcOffset": 9
        }, {
            "cityName": "Riga",
            "utcOffset": 3
        }, {
            "cityName": "Beirut",
            "utcOffset": 3
        }, {
            "cityName": "Kazan",
            "utcOffset": 3
        }, {
            "cityName": "Rio Branco",
            "utcOffset": -5
        }, {
            "cityName": "Belém",
            "utcOffset": -3
        }, {
            "cityName": "Kemi",
            "utcOffset": 3
        }, {
            "cityName": "Rio de Janeiro",
            "utcOffset": -3
        }, {
            "cityName": "Belfast",
            "utcOffset": 1
        }, {
            "cityName": "Kendari",
            "utcOffset": 8
        }, {
            "cityName": "Riyadh",
            "utcOffset": 3
        }, {
            "cityName": "Belgrade",
            "utcOffset": 2
        }, {
            "cityName": "Khartoum",
            "utcOffset": 3
        }, {
            "cityName": "Rome",
            "utcOffset": 2
        }, {
            "cityName": "Belmopan",
            "utcOffset": -6
        }, {
            "cityName": "Khatanga",
            "utcOffset": 7
        }, {
            "cityName": "Rosario",
            "utcOffset": -3
        }, {
            "cityName": "Belushya Guba",
            "utcOffset": 3
        }, {
            "cityName": "Khon Kaen",
            "utcOffset": 7
        }, {
            "cityName": "Roseau",
            "utcOffset": -4
        }, {
            "cityName": "Bengaluru",
            "utcOffset": 5.5
        }, {
            "cityName": "Kigali",
            "utcOffset": 2
        }, {
            "cityName": "Rotterdam",
            "utcOffset": 2
        }, {
            "cityName": "Bengkulu",
            "utcOffset": 7
        }, {
            "cityName": "King Edward Point",
            "utcOffset": -2
        }, {
            "cityName": "Rovaniemi",
            "utcOffset": 3
        }, {
            "cityName": "Berlin",
            "utcOffset": 2
        }, {
            "cityName": "Kingston",
            "utcOffset": -5
        }, {
            "cityName": "Ryazan",
            "utcOffset": 3
        }, {
            "cityName": "Bern",
            "utcOffset": 2
        }, {
            "cityName": "Kingstown",
            "utcOffset": -4
        }, {
            "cityName": "Sacramento",
            "utcOffset": -7
        }, {
            "cityName": "Bethlehem",
            "utcOffset": 3
        }, {
            "cityName": "Kinshasa",
            "utcOffset": 1
        }, {
            "cityName": "Sagamihara",
            "utcOffset": 9
        }, {
            "cityName": "Bhubaneshwar",
            "utcOffset": 5.5
        }, {
            "cityName": "Kiritimati",
            "utcOffset": 14
        }, {
            "cityName": "Saint-Denis",
            "utcOffset": 4
        }, {
            "cityName": "Billings",
            "utcOffset": -6
        }, {
            "cityName": "Kitakyushu",
            "utcOffset": 9
        }, {
            "cityName": "Saint George's",
            "utcOffset": -4
        }, {
            "cityName": "Birmingham",
            "utcOffset": 1
        }, {
            "cityName": "Knoxville",
            "utcOffset": -4
        }, {
            "cityName": "Saint John (CA - NB)",
            "utcOffset": -3
        }, {
            "cityName": "Bishkek",
            "utcOffset": 6
        }, {
            "cityName": "Kobe",
            "utcOffset": 9
        }, {
            "cityName": "Saint John's (Antigua)",
            "utcOffset": -4
        }, {
            "cityName": "Bismarck",
            "utcOffset": -5
        }, {
            "cityName": "Kolkata",
            "utcOffset": 5.5
        }, {
            "cityName": "Saint-Petersburg",
            "utcOffset": 3
        }, {
            "cityName": "Bissau",
            "utcOffset": 0
        }, {
            "cityName": "Komsomolsk-on-Amur",
            "utcOffset": 10
        }, {
            "cityName": "Salem",
            "utcOffset": -7
        }, {
            "cityName": "Blanc-Sablon",
            "utcOffset": -4
        }, {
            "cityName": "Kowloon",
            "utcOffset": 8
        }, {
            "cityName": "Salt Lake City",
            "utcOffset": -6
        }, {
            "cityName": "Bogota",
            "utcOffset": -5
        }, {
            "cityName": "Krasnoyarsk",
            "utcOffset": 7
        }, {
            "cityName": "Salvador",
            "utcOffset": -3
        }, {
            "cityName": "Boise",
            "utcOffset": -6
        }, {
            "cityName": "Kuala Lumpur",
            "utcOffset": 8
        }, {
            "cityName": "Samara",
            "utcOffset": 4
        }, {
            "cityName": "Boston",
            "utcOffset": -4
        }, {
            "cityName": "Kumamoto",
            "utcOffset": 9
        }, {
            "cityName": "San Diego",
            "utcOffset": -7
        }, {
            "cityName": "Brampton",
            "utcOffset": -4
        }, {
            "cityName": "Kunming",
            "utcOffset": 8
        }, {
            "cityName": "San Francisco",
            "utcOffset": -7
        }, {
            "cityName": "Brasilia",
            "utcOffset": -3
        }, {
            "cityName": "Kuujjuaq",
            "utcOffset": -4
        }, {
            "cityName": "San Jose (CR)",
            "utcOffset": -6
        }, {
            "cityName": "Bratislava",
            "utcOffset": 2
        }, {
            "cityName": "Kuwait City",
            "utcOffset": 3
        }, {
            "cityName": "San Jose (USA)",
            "utcOffset": -7
        }, {
            "cityName": "Brazzaville",
            "utcOffset": 1
        }, {
            "cityName": "Kyiv",
            "utcOffset": 3
        }, {
            "cityName": "San Juan",
            "utcOffset": -4
        }, {
            "cityName": "Bridgetown",
            "utcOffset": -4
        }, {
            "cityName": "Kyoto",
            "utcOffset": 9
        }, {
            "cityName": "San Luis Potosi",
            "utcOffset": -5
        }, {
            "cityName": "Brisbane",
            "utcOffset": 10
        }, {
            "cityName": "La Paz",
            "utcOffset": -4
        }, {
            "cityName": "San Marino",
            "utcOffset": 2
        }, {
            "cityName": "Brussels",
            "utcOffset": 2
        }, {
            "cityName": "Lagos",
            "utcOffset": 1
        }, {
            "cityName": "San Salvador",
            "utcOffset": -6
        }, {
            "cityName": "Bucharest",
            "utcOffset": 3
        }, {
            "cityName": "Lahore",
            "utcOffset": 5
        }, {
            "cityName": "Sana",
            "utcOffset": 3
        }, {
            "cityName": "Budapest",
            "utcOffset": 2
        }, {
            "cityName": "Lanchow",
            "utcOffset": 8
        }, {
            "cityName": "Santa Ana",
            "utcOffset": -6
        }, {
            "cityName": "Buenos Aires",
            "utcOffset": -3
        }, {
            "cityName": "Lanzhou",
            "utcOffset": 8
        }, {
            "cityName": "Santa Fe",
            "utcOffset": -6
        }, {
            "cityName": "Bujumbura",
            "utcOffset": 2
        }, {
            "cityName": "Las Vegas",
            "utcOffset": -7
        }, {
            "cityName": "Santiago",
            "utcOffset": -3
        }, {
            "cityName": "Bursa",
            "utcOffset": 3
        }, {
            "cityName": "Laval",
            "utcOffset": -4
        }, {
            "cityName": "Santo Domingo",
            "utcOffset": -4
        }, {
            "cityName": "Busan",
            "utcOffset": 9
        }, {
            "cityName": "Leon",
            "utcOffset": -5
        }, {
            "cityName": "São Paulo",
            "utcOffset": -3
        }, {
            "cityName": "Cairns",
            "utcOffset": 10
        }, {
            "cityName": "Leshan",
            "utcOffset": 8
        }, {
            "cityName": "São Tomé",
            "utcOffset": 0
        }, {
            "cityName": "Cairo",
            "utcOffset": 2
        }, {
            "cityName": "Lhasa",
            "utcOffset": 8
        }, {
            "cityName": "Sapporo",
            "utcOffset": 9
        }, {
            "cityName": "Calgary",
            "utcOffset": -6
        }, {
            "cityName": "Libreville",
            "utcOffset": 1
        }, {
            "cityName": "Sarajevo",
            "utcOffset": 2
        }, {
            "cityName": "Cali",
            "utcOffset": -5
        }, {
            "cityName": "Lilongwe",
            "utcOffset": 2
        }, {
            "cityName": "Saskatoon",
            "utcOffset": -6
        }, {
            "cityName": "Canberra",
            "utcOffset": 10
        }, {
            "cityName": "Lima",
            "utcOffset": -5
        }, {
            "cityName": "Seattle",
            "utcOffset": -7
        }, {
            "cityName": "Cancún",
            "utcOffset": -5
        }, {
            "cityName": "Lincoln",
            "utcOffset": -5
        }, {
            "cityName": "Semarang",
            "utcOffset": 7
        }, {
            "cityName": "Cape Town",
            "utcOffset": 2
        }, {
            "cityName": "Lisbon",
            "utcOffset": 1
        }, {
            "cityName": "Seoul",
            "utcOffset": 9
        }, {
            "cityName": "Caracas",
            "utcOffset": -4
        }, {
            "cityName": "Little Rock",
            "utcOffset": -5
        }, {
            "cityName": "Shanghai",
            "utcOffset": 8
        }, {
            "cityName": "Cardiff",
            "utcOffset": 1
        }, {
            "cityName": "Liverpool",
            "utcOffset": 1
        }, {
            "cityName": "Shantou",
            "utcOffset": 8
        }, {
            "cityName": "Carson City",
            "utcOffset": -7
        }, {
            "cityName": "Ljubljana",
            "utcOffset": 2
        }, {
            "cityName": "Shenyang",
            "utcOffset": 8
        }, {
            "cityName": "Casablanca",
            "utcOffset": 1
        }, {
            "cityName": "Lomé",
            "utcOffset": 0
        }, {
            "cityName": "Shenzhen",
            "utcOffset": 8
        }, {
            "cityName": "Castries",
            "utcOffset": -4
        }, {
            "cityName": "London (Canada)",
            "utcOffset": -4
        }, {
            "cityName": "Shijiazhuang",
            "utcOffset": 8
        }, {
            "cityName": "Cayenne",
            "utcOffset": -3
        }, {
            "cityName": "London (U.K.)",
            "utcOffset": 1
        }, {
            "cityName": "Shizuoka",
            "utcOffset": 9
        }, {
            "cityName": "Changchun",
            "utcOffset": 8
        }, {
            "cityName": "Long Beach",
            "utcOffset": -7
        }, {
            "cityName": "Sikeston",
            "utcOffset": -5
        }, {
            "cityName": "Changde",
            "utcOffset": 8
        }, {
            "cityName": "Longueuil",
            "utcOffset": -4
        }, {
            "cityName": "Singapore",
            "utcOffset": 8
        }, {
            "cityName": "Changsha",
            "utcOffset": 8
        }, {
            "cityName": "Longyearbyen",
            "utcOffset": 2
        }, {
            "cityName": "Sioux Falls",
            "utcOffset": -5
        }, {
            "cityName": "Charleston",
            "utcOffset": -4
        }, {
            "cityName": "Los Angeles",
            "utcOffset": -7
        }, {
            "cityName": "Skopje",
            "utcOffset": 2
        }, {
            "cityName": "Charlotte",
            "utcOffset": -4
        }, {
            "cityName": "Louisville",
            "utcOffset": -4
        }, {
            "cityName": "Sofia",
            "utcOffset": 3
        }, {
            "cityName": "Chatham Islands",
            "utcOffset": 12.75
        }, {
            "cityName": "Luanda",
            "utcOffset": 1
        }, {
            "cityName": "Srednekolymsk",
            "utcOffset": 11
        }, {
            "cityName": "Chelyabinsk",
            "utcOffset": 5
        }, {
            "cityName": "Lubumbashi",
            "utcOffset": 2
        }, {
            "cityName": "Sri Jayawardenapura Kotte",
            "utcOffset": 5.5
        }, {
            "cityName": "Chengdu",
            "utcOffset": 8
        }, {
            "cityName": "Lucknow",
            "utcOffset": 5.5
        }, {
            "cityName": "St. John's (CA - NF)",
            "utcOffset": -2.5
        }, {
            "cityName": "Chennai",
            "utcOffset": 5.5
        }, {
            "cityName": "Ludhiana",
            "utcOffset": 5.5
        }, {
            "cityName": "St. Louis",
            "utcOffset": -5
        }, {
            "cityName": "Cheyenne",
            "utcOffset": -6
        }, {
            "cityName": "Luoyang",
            "utcOffset": 8
        }, {
            "cityName": "St. Paul",
            "utcOffset": -5
        }, {
            "cityName": "Chibougamau",
            "utcOffset": -4
        }, {
            "cityName": "Lusaka",
            "utcOffset": 2
        }, {
            "cityName": "Stanley",
            "utcOffset": -3
        }, {
            "cityName": "Chicago",
            "utcOffset": -5
        }, {
            "cityName": "Luxembourg",
            "utcOffset": 2
        }, {
            "cityName": "Stockholm",
            "utcOffset": 2
        }, {
            "cityName": "Chihuahua",
            "utcOffset": -6
        }, {
            "cityName": "Madison",
            "utcOffset": -5
        }, {
            "cityName": "Stuttgart",
            "utcOffset": 2
        }, {
            "cityName": "Chita",
            "utcOffset": 9
        }, {
            "cityName": "Madrid",
            "utcOffset": 2
        }, {
            "cityName": "Sucre",
            "utcOffset": -4
        }, {
            "cityName": "Chittagong",
            "utcOffset": 6
        }, {
            "cityName": "Madurai",
            "utcOffset": 5.5
        }, {
            "cityName": "Surabaya",
            "utcOffset": 7
        }, {
            "cityName": "Chișinău",
            "utcOffset": 3
        }, {
            "cityName": "Magadan",
            "utcOffset": 11
        }, {
            "cityName": "Surakarta",
            "utcOffset": 7
        }, {
            "cityName": "Chongqing",
            "utcOffset": 8
        }, {
            "cityName": "Majuro",
            "utcOffset": 12
        }, {
            "cityName": "Surat",
            "utcOffset": 5.5
        }, {
            "cityName": "Cincinnati",
            "utcOffset": -4
        }, {
            "cityName": "Makassar",
            "utcOffset": 8
        }, {
            "cityName": "Suva",
            "utcOffset": 12
        }, {
            "cityName": "Ciudad Juárez",
            "utcOffset": -6
        }, {
            "cityName": "Makkah",
            "utcOffset": 3
        }, {
            "cityName": "Suzhou",
            "utcOffset": 8
        }, {
            "cityName": "Cleveland",
            "utcOffset": -4
        }, {
            "cityName": "Malabo",
            "utcOffset": 1
        }, {
            "cityName": "Sydney",
            "utcOffset": 10
        }, {
            "cityName": "Colombo",
            "utcOffset": 5.5
        }, {
            "cityName": "Malang",
            "utcOffset": 7
        }, {
            "cityName": "Taipei",
            "utcOffset": 8
        }, {
            "cityName": "Columbia",
            "utcOffset": -4
        }, {
            "cityName": "Male",
            "utcOffset": 5
        }, {
            "cityName": "Taiyuan",
            "utcOffset": 8
        }, {
            "cityName": "Columbus",
            "utcOffset": -4
        }, {
            "cityName": "Manado",
            "utcOffset": 8
        }, {
            "cityName": "Tallinn",
            "utcOffset": 3
        }, {
            "cityName": "Conakry",
            "utcOffset": 0
        }, {
            "cityName": "Managua",
            "utcOffset": -6
        }, {
            "cityName": "Tampa",
            "utcOffset": -4
        }, {
            "cityName": "Concord",
            "utcOffset": -4
        }, {
            "cityName": "Manama",
            "utcOffset": 3
        }, {
            "cityName": "Tangier",
            "utcOffset": 1
        }, {
            "cityName": "Copenhagen",
            "utcOffset": 2
        }, {
            "cityName": "Manaus",
            "utcOffset": -4
        }, {
            "cityName": "Tangshan",
            "utcOffset": 8
        }, {
            "cityName": "Coral Harbour",
            "utcOffset": -5
        }, {
            "cityName": "Mandalay",
            "utcOffset": 6.5
        }, {
            "cityName": "Tarawa",
            "utcOffset": 12
        }, {
            "cityName": "Córdoba (Arg)",
            "utcOffset": -3
        }, {
            "cityName": "Manila",
            "utcOffset": 8
        }, {
            "cityName": "Tashkent",
            "utcOffset": 5
        }, {
            "cityName": "Córdoba (Spain)",
            "utcOffset": 2
        }, {
            "cityName": "Manokwari",
            "utcOffset": 9
        }, {
            "cityName": "Tbilisi",
            "utcOffset": 4
        }, {
            "cityName": "Daegu",
            "utcOffset": 9
        }, {
            "cityName": "Maputo",
            "utcOffset": 2
        }, {
            "cityName": "Tegucigalpa",
            "utcOffset": -6
        }, {
            "cityName": "Dakar",
            "utcOffset": 0
        }, {
            "cityName": "Marion Island (Prince Edward Islands)",
            "utcOffset": 3
        }, {
            "cityName": "Tehran",
            "utcOffset": 4.5
        }, {
            "cityName": "Dalian",
            "utcOffset": 8
        }, {
            "cityName": "Marrakech",
            "utcOffset": 1
        }, {
            "cityName": "Tel Aviv",
            "utcOffset": 3
        }, {
            "cityName": "Dallas",
            "utcOffset": -5
        }, {
            "cityName": "Mary's Harbour",
            "utcOffset": -2.5
        }, {
            "cityName": "Thimphu",
            "utcOffset": 6
        }, {
            "cityName": "Damascus",
            "utcOffset": 3
        }, {
            "cityName": "Maseru",
            "utcOffset": 2
        }, {
            "cityName": "Thiruvananthapuram",
            "utcOffset": 5.5
        }, {
            "cityName": "Danmarkshavn",
            "utcOffset": 0
        }, {
            "cityName": "Matsuyama",
            "utcOffset": 9
        }, {
            "cityName": "Thule Air Base",
            "utcOffset": -3
        }, {
            "cityName": "Dar es Salaam",
            "utcOffset": 3
        }, {
            "cityName": "Mazatlan",
            "utcOffset": -6
        }, {
            "cityName": "Tianjin",
            "utcOffset": 8
        }, {
            "cityName": "Darwin",
            "utcOffset": 9.5
        }, {
            "cityName": "Mbabane",
            "utcOffset": 2
        }, {
            "cityName": "Tijuana",
            "utcOffset": -7
        }, {
            "cityName": "Davao",
            "utcOffset": 8
        }, {
            "cityName": "Medan",
            "utcOffset": 7
        }, {
            "cityName": "Tiksi",
            "utcOffset": 9
        }, {
            "cityName": "Delhi",
            "utcOffset": 5.5
        }, {
            "cityName": "Medellin",
            "utcOffset": -5
        }, {
            "cityName": "Timbuktu",
            "utcOffset": 0
        }, {
            "cityName": "Denpasar",
            "utcOffset": 8
        }, {
            "cityName": "Medina",
            "utcOffset": 3
        }, {
            "cityName": "Tirana",
            "utcOffset": 2
        }, {
            "cityName": "Denver",
            "utcOffset": -6
        }, {
            "cityName": "Melbourne",
            "utcOffset": 10
        }, {
            "cityName": "Tokyo",
            "utcOffset": 9
        }, {
            "cityName": "Des Moines",
            "utcOffset": -5
        }, {
            "cityName": "Melekeok",
            "utcOffset": 9
        }, {
            "cityName": "Toledo",
            "utcOffset": -4
        }, {
            "cityName": "Detroit",
            "utcOffset": -4
        }, {
            "cityName": "Memphis",
            "utcOffset": -5
        }, {
            "cityName": "Topeka",
            "utcOffset": -5
        }, {
            "cityName": "Dhaka",
            "utcOffset": 6
        }, {
            "cityName": "Mendoza",
            "utcOffset": -3
        }, {
            "cityName": "Toronto",
            "utcOffset": -4
        }, {
            "cityName": "Diego Garcia",
            "utcOffset": 6
        }, {
            "cityName": "Merida",
            "utcOffset": -5
        }, {
            "cityName": "Tórshavn",
            "utcOffset": 1
        }, {
            "cityName": "Dili",
            "utcOffset": 9
        }, {
            "cityName": "Mexicali",
            "utcOffset": -7
        }, {
            "cityName": "Trenton",
            "utcOffset": -4
        }, {
            "cityName": "Djibouti",
            "utcOffset": 3
        }, {
            "cityName": "Mexico City",
            "utcOffset": -5
        }, {
            "cityName": "Tripoli",
            "utcOffset": 2
        }, {
            "cityName": "Dnipro",
            "utcOffset": 3
        }, {
            "cityName": "Miami",
            "utcOffset": -4
        }, {
            "cityName": "Tromsø",
            "utcOffset": 2
        }, {
            "cityName": "Dodoma",
            "utcOffset": 3
        }, {
            "cityName": "Midland",
            "utcOffset": -5
        }, {
            "cityName": "Tsingtao",
            "utcOffset": 8
        }, {
            "cityName": "Doha",
            "utcOffset": 3
        }, {
            "cityName": "Midway",
            "utcOffset": -11
        }, {
            "cityName": "Tucson",
            "utcOffset": -7
        }, {
            "cityName": "Douglas",
            "utcOffset": 1
        }, {
            "cityName": "Milan",
            "utcOffset": 2
        }, {
            "cityName": "Tunis",
            "utcOffset": 1
        }, {
            "cityName": "Dover",
            "utcOffset": -4
        }, {
            "cityName": "Milwaukee",
            "utcOffset": -5
        }, {
            "cityName": "Turin",
            "utcOffset": 2
        }, {
            "cityName": "Dubai",
            "utcOffset": 4
        }, {
            "cityName": "Minneapolis",
            "utcOffset": -5
        }, {
            "cityName": "Ufa",
            "utcOffset": 5
        }, {
            "cityName": "Dublin",
            "utcOffset": 1
        }, {
            "cityName": "Minsk",
            "utcOffset": 3
        }, {
            "cityName": "Ulaanbaatar",
            "utcOffset": 9
        }, {
            "cityName": "Durban",
            "utcOffset": 2
        }, {
            "cityName": "Mississauga",
            "utcOffset": -4
        }, {
            "cityName": "Unalaska",
            "utcOffset": -8
        }, {
            "cityName": "Dushanbe",
            "utcOffset": 5
        }, {
            "cityName": "Mogadishu",
            "utcOffset": 3
        }, {
            "cityName": "Ürümqi",
            "utcOffset": 8
        }, {
            "cityName": "Düsseldorf",
            "utcOffset": 2
        }, {
            "cityName": "Monaco",
            "utcOffset": 2
        }, {
            "cityName": "Utsunomiya",
            "utcOffset": 9
        }, {
            "cityName": "Easter Island",
            "utcOffset": -5
        }, {
            "cityName": "Monrovia",
            "utcOffset": 0
        }, {
            "cityName": "Vaduz",
            "utcOffset": 2
        }, {
            "cityName": "Edinburgh",
            "utcOffset": 1
        }, {
            "cityName": "Montevideo",
            "utcOffset": -3
        }, {
            "cityName": "Valletta",
            "utcOffset": 2
        }, {
            "cityName": "Edmonton",
            "utcOffset": -6
        }, {
            "cityName": "Montgomery",
            "utcOffset": -5
        }, {
            "cityName": "Vancouver",
            "utcOffset": -7
        }, {
            "cityName": "El Aaiún",
            "utcOffset": 1
        }, {
            "cityName": "Montpelier",
            "utcOffset": -4
        }, {
            "cityName": "Varanasi",
            "utcOffset": 5.5
        }, {
            "cityName": "El Paso",
            "utcOffset": -6
        }, {
            "cityName": "Montreal",
            "utcOffset": -4
        }, {
            "cityName": "Vatican City",
            "utcOffset": 2
        }, {
            "cityName": "Eucla",
            "utcOffset": 8.75
        }, {
            "cityName": "Moroni",
            "utcOffset": 3
        }, {
            "cityName": "Venice",
            "utcOffset": 2
        }, {
            "cityName": "Eureka",
            "utcOffset": -5
        }, {
            "cityName": "Moscow",
            "utcOffset": 3
        }, {
            "cityName": "Veracruz",
            "utcOffset": -5
        }, {
            "cityName": "Fairbanks",
            "utcOffset": -8
        }, {
            "cityName": "Mudanjiang",
            "utcOffset": 8
        }, {
            "cityName": "Verkhoyansk",
            "utcOffset": 10
        }, {
            "cityName": "Faisalabad",
            "utcOffset": 5
        }, {
            "cityName": "Multan",
            "utcOffset": 5
        }, {
            "cityName": "Victoria",
            "utcOffset": 4
        }, {
            "cityName": "Fakaofo",
            "utcOffset": 13
        }, {
            "cityName": "Mumbai",
            "utcOffset": 5.5
        }, {
            "cityName": "Vienna",
            "utcOffset": 2
        }, {
            "cityName": "Fargo",
            "utcOffset": -5
        }, {
            "cityName": "Munich",
            "utcOffset": 2
        }, {
            "cityName": "Vientiane",
            "utcOffset": 7
        }, {
            "cityName": "Fayetteville",
            "utcOffset": -4
        }, {
            "cityName": "Murmansk",
            "utcOffset": 3
        }, {
            "cityName": "Vilnius",
            "utcOffset": 3
        }, {
            "cityName": "Fes",
            "utcOffset": 1
        }, {
            "cityName": "Muscat",
            "utcOffset": 4
        }, {
            "cityName": "Virginia Beach",
            "utcOffset": -4
        }, {
            "cityName": "Foochow",
            "utcOffset": 8
        }, {
            "cityName": "Nagoya",
            "utcOffset": 9
        }, {
            "cityName": "Visakhapatnam",
            "utcOffset": 5.5
        }, {
            "cityName": "Fort-de-France",
            "utcOffset": -4
        }, {
            "cityName": "Nãgpur",
            "utcOffset": 5.5
        }, {
            "cityName": "Vladivostok",
            "utcOffset": 10
        }, {
            "cityName": "Fortaleza",
            "utcOffset": -3
        }, {
            "cityName": "Nairobi",
            "utcOffset": 3
        }, {
            "cityName": "Wake Island",
            "utcOffset": 12
        }, {
            "cityName": "Foshan",
            "utcOffset": 8
        }, {
            "cityName": "Nanchang",
            "utcOffset": 8
        }, {
            "cityName": "Warsaw",
            "utcOffset": 2
        }, {
            "cityName": "Frankfort (US)",
            "utcOffset": -4
        }, {
            "cityName": "Nanjing",
            "utcOffset": 8
        }, {
            "cityName": "Washington DC",
            "utcOffset": -4
        }, {
            "cityName": "Frankfurt (Ger)",
            "utcOffset": 2
        }, {
            "cityName": "Nanning",
            "utcOffset": 8
        }, {
            "cityName": "Wellington",
            "utcOffset": 12
        }, {
            "cityName": "Freetown",
            "utcOffset": 0
        }, {
            "cityName": "Naples",
            "utcOffset": 2
        }, {
            "cityName": "Whitehorse",
            "utcOffset": -7
        }, {
            "cityName": "Fresno",
            "utcOffset": -7
        }, {
            "cityName": "Nashville",
            "utcOffset": -5
        }, {
            "cityName": "Wichita",
            "utcOffset": -5
        }, {
            "cityName": "Fukuoka",
            "utcOffset": 9
        }, {
            "cityName": "Nassau",
            "utcOffset": -4
        }, {
            "cityName": "Windhoek",
            "utcOffset": 1
        }, {
            "cityName": "Funafuti",
            "utcOffset": 12
        }, {
            "cityName": "Naypyidaw",
            "utcOffset": 6.5
        }, {
            "cityName": "Winnipeg",
            "utcOffset": -5
        }, {
            "cityName": "Fushun",
            "utcOffset": 8
        }, {
            "cityName": "Ndjamena",
            "utcOffset": 1
        }, {
            "cityName": "Wuhan",
            "utcOffset": 8
        }, {
            "cityName": "Gaborone",
            "utcOffset": 2
        }, {
            "cityName": "New Delhi",
            "utcOffset": 5.5
        }, {
            "cityName": "Xi'an",
            "utcOffset": 8
        }, {
            "cityName": "Galapagos Islands",
            "utcOffset": -6
        }, {
            "cityName": "New Orleans",
            "utcOffset": -5
        }, {
            "cityName": "Xiamen",
            "utcOffset": 8
        }, {
            "cityName": "Gaza",
            "utcOffset": 3
        }, {
            "cityName": "New York",
            "utcOffset": -4
        }, {
            "cityName": "Xinyang",
            "utcOffset": 8
        }, {
            "cityName": "General Santos",
            "utcOffset": 8
        }, {
            "cityName": "Newark",
            "utcOffset": -4
        }, {
            "cityName": "Yakutsk",
            "utcOffset": 9
        }, {
            "cityName": "Geneva",
            "utcOffset": 2
        }, {
            "cityName": "Niamey",
            "utcOffset": 1
        }, {
            "cityName": "Yamoussoukro",
            "utcOffset": 0
        }, {
            "cityName": "George Town (Cayman)",
            "utcOffset": -5
        }, {
            "cityName": "Nice",
            "utcOffset": 2
        }, {
            "cityName": "Yangon",
            "utcOffset": 6.5
        }, {
            "cityName": "Georgetown (Guyana)",
            "utcOffset": -4
        }, {
            "cityName": "Nicosia",
            "utcOffset": 3
        }, {
            "cityName": "Yaoundé",
            "utcOffset": 1
        }, {
            "cityName": "Gibraltar",
            "utcOffset": 2
        }, {
            "cityName": "Niigata",
            "utcOffset": 9
        }, {
            "cityName": "Yaren",
            "utcOffset": 12
        }, {
            "cityName": "Glasgow",
            "utcOffset": 1
        }, {
            "cityName": "Nizhny Novgorod",
            "utcOffset": 3
        }, {
            "cityName": "Yekaterinburg",
            "utcOffset": 5
        }, {
            "cityName": "Gorontalo",
            "utcOffset": 8
        }, {
            "cityName": "Norilsk",
            "utcOffset": 7
        }, {
            "cityName": "Yellowknife",
            "utcOffset": -6
        }, {
            "cityName": "Grise Fiord",
            "utcOffset": -4
        }, {
            "cityName": "Nouakchott",
            "utcOffset": 0
        }, {
            "cityName": "Yerevan",
            "utcOffset": 4
        }, {
            "cityName": "Guadalajara",
            "utcOffset": -5
        }, {
            "cityName": "Noumea",
            "utcOffset": 11
        }, {
            "cityName": "Yokohama",
            "utcOffset": 9
        }, {
            "cityName": "Guangzhou",
            "utcOffset": 8
        }, {
            "cityName": "Novgorod",
            "utcOffset": 3
        }, {
            "cityName": "Yuzhno-Sakhalinsk",
            "utcOffset": 11
        }, {
            "cityName": "Guatemala",
            "utcOffset": -6
        }, {
            "cityName": "Novosibirsk",
            "utcOffset": 7
        }, {
            "cityName": "Zagreb",
            "utcOffset": 2
        }, {
            "cityName": "Guayaquil",
            "utcOffset": -5
        }, {
            "cityName": "Nukualofa",
            "utcOffset": 13
        }, {
            "cityName": "Zhengzhou",
            "utcOffset": 8
        }, {
            "cityName": "Guiyang",
            "utcOffset": 8
        }, {
            "cityName": "Nuuk",
            "utcOffset": -2
        }, {
            "cityName": "Zibo",
            "utcOffset": 8
        }, {
            "cityName": "Gujranwala",
            "utcOffset": 5
        }, {
            "cityName": "Oakland",
            "utcOffset": -7
        }, {
            "cityName": "Zürich",
            "utcOffset": 2
        }, {
            "cityName": "Hafizabad",
            "utcOffset": 5
        }, {
            "cityName": "Odesa",
            "utcOffset": 3
        }];

        return Tardis;
    }]);
}());
